### ISSUE TITLE
Can't add prom-label-proxy as a Grafana data source

### ISSUE THREAD

**Issue by IbraheemAlSaady** [prometheus-community/prom-label-proxy#57]
I'm trying to add the prom-label-proxy as a Prometheus data source but I'm not successful. I'm only using the label proxy for testing, here is my config:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-rbac-proxy
  namespace: monitoring
  labels:
    app: kube-rbac-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-rbac-proxy
  template:
    metadata:
      labels:
        app: kube-rbac-proxy
    spec:
      containers:
      - name: prom-label-enforcer
        image: quay.io/coreos/prom-label-proxy:v0.1.0
        imagePullPolicy: Always
        args:
        - "--insecure-listen-address=127.0.0.1:8080"
        - "--upstream=http://thanos-query.monitoring.svc:9090/"
        - "--label=namespace"
        ports:
        - containerPort: 8080
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: kube-rbac-proxy
  namespace: monitoring
  labels:
    app: kube-rbac-proxy
spec:
  selector:
    app: kube-rbac-proxy
  ports:
  - name: http
    port: 8080
    targetPort: 8080
```

I'm getting this error when I add the data source.

`Unknown error during query transaction. Please check JS console logs.`

here is the JS Console

`GET https://[Grafana-Host]/api/datasources/proxy/3/api/v1/query?query=1%2B1&time=1612350247.932&namespace=monitoring 502`

The Url of the data source is this `kube-rbac-proxy.monitoring:8080`
