### ISSUE TITLE
prom-label-proxy refusing to proxy for Grafana even if the required label is specified

### ISSUE THREAD

**Issue by amine250** [prometheus-community/prom-label-proxy#74]
Hello,

I have a Grafana instance with a datasource that points to prom-label-proxy which is in front of a Thanos/Prometheus cluster.

The datasource is configured as below:

![image](https://user-images.githubusercontent.com/7514608/127346949-2225f6ec-294b-438d-bf83-a6e4503722b3.png)

The prom-label-proxy is running in EKS as a sidecar, with the following arguments:
```yaml
- name: prom-label-proxy
        image: quay.io/prometheuscommunity/prom-label-proxy:v0.3.0
        args:
        - --label=perimeter
        - --upstream=http://127.0.0.1:10902
        - --insecure-listen-address=0.0.0.0:8080
        - --unsafe-passthrough-paths=/-/ready
```

When I issue the following query in Grafana, I get the following response:

![image](https://user-images.githubusercontent.com/7514608/127347330-591a4bc5-63f5-430b-8389-a908ff0893c3.png)

![image](https://user-images.githubusercontent.com/7514608/127347294-b2fbbf45-0713-41c3-a514-23e646d6f49a.png)

When I configure my datasource to always have the query param `perimeter` set, it works, but it's not good since I would have to create a separate datasource for each value of `perimeter`:
![image](https://user-images.githubusercontent.com/7514608/127347933-2431fb29-4dba-4d46-b881-7e3d3da2d230.png)
